# Generated by Django 5.2.6 on 2025-09-09 15:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Whiteboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stroke',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stroke_id', models.UUIDField()),
                ('user_id', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(default='#000', max_length=32)),
                ('points', models.JSONField(default=list)),
                ('finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('whiteboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strokes', to='WS.whiteboard')),
            ],
            options={
                'indexes': [models.Index(fields=['whiteboard', 'stroke_id'], name='WS_stroke_whitebo_080cce_idx')],
                'unique_together': {('whiteboard', 'stroke_id')},
            },
        ),
    ]
